name = "eds-slack-channels-worker"
main = "src/main.js"
compatibility_date = "2025-04-28"
workers_dev = true
preview_urls = false

[[kv_namespaces]]
binding = "SLACK_KV"
id = "5de564f59467495eac69245058ddb9b0"


[triggers]
crons = ["0 0 * * *"]  # every 24 hours at midnight

[[queues.producers]]
queue = "slack-stats-queue"
binding = "SLACK_STATS_QUEUE"

[[queues.consumers]]
queue = "slack-stats-queue"
binding = "SLACK_STATS_QUEUE"
